services:
  wechat-ocr-api:
    build: .
    ports:
      - "7777:5000"
    container_name: wechat-ocr-api
  
  # 使用预构建的镜像
  # wechat-ocr-api:
  #   image: golangboyme/wxocr
  #   ports:
  #     - "5000:5000"
  #   container_name: wechat-ocr-api